import { Climb, modelCatalog } from "./climbs";

const hourlyVars = "temperature_2m,precipitation,rain,snowfall,pressure_msl,wind_speed_10m";
const avg = (v:number[]) => v.length ? v.reduce((a,b)=>a+b,0)/v.length : 0;
const sum = (v:number[]) => v.reduce((a,b)=>a+b,0);
const max = (v:number[]) => v.length ? Math.max(...v) : 0;
const spread = (v:number[]) => v.length > 1 ? Math.max(...v) - Math.min(...v) : 0;
const pick = (hourly:any, key:string, indices:number[]) => indices.map(i => hourly?.[key]?.[i]).filter((v:any)=>typeof v === "number");
const clampScore = (v:number) => Math.max(0, Math.min(10, Number(v)||0));

function getRegion(climb:Climb) { return climb.region.includes("Washington") ? "usa" : "canada"; }
function applies(model:any, climb:Climb) { const region = getRegion(climb); return model.regions.includes("global") || model.regions.includes(region); }
function elevationProfile(climb:Climb) { const valleyM = climb.id === "robson-kain" ? 800 : climb.id === "adams-sw-chutes" ? 1700 : climb.id === "temple-aemmer" ? 1800 : 1500; return { summitM: climb.summitM, midM: Math.round((climb.summitM + valleyM)/2), valleyM }; }
function groupHourlyByDay(hourly:any) { const rows:any[] = []; (hourly?.time || []).forEach((time:string, index:number) => { const date = time.slice(0,10); let row = rows.find(r=>r.date===date); if (!row) { row = { date, indices: [] }; rows.push(row); } row.indices.push(index); }); return rows; }
function summarize(row:any, hourly:any) { const temps = pick(hourly,"temperature_2m",row?.indices||[]); return { tempAvg:+avg(temps).toFixed(1), tempMin:+(temps.length?Math.min(...temps):0).toFixed(1), tempMax:+(temps.length?Math.max(...temps):0).toFixed(1), windMax:Math.round(max(pick(hourly,"wind_speed_10m",row?.indices||[]))), rainMm:+sum(pick(hourly,"rain",row?.indices||[])).toFixed(1), snowCm:+sum(pick(hourly,"snowfall",row?.indices||[])).toFixed(1), precipMm:+sum(pick(hourly,"precipitation",row?.indices||[])).toFixed(1), pressure:Math.round(avg(pick(hourly,"pressure_msl",row?.indices||[]))) }; }
function freezingLevel(valley:any, mid:any, summit:any, elev:any) { const pts = [{e:elev.valleyM,t:valley.tempAvg},{e:elev.midM,t:mid.tempAvg},{e:elev.summitM,t:summit.tempAvg}].sort((a,b)=>a.e-b.e); if (pts[0].t <= 0) return pts[0].e; if (pts[2].t >= 0) return pts[2].e; for (let i=0;i<2;i++){ const l=pts[i], u=pts[i+1]; if(l.t>=0&&u.t<=0){ const r=l.t/Math.max(0.1,l.t-u.t); return Math.round(l.e+r*(u.e-l.e)); }} return pts[1].e; }

async function fetchElevation(climb:Climb, model:any, elevationM:number) {
  const modelPart = model.id === "best_match" ? "" : `&models=${model.id}`;
  const url = `https://api.open-meteo.com/v1/forecast?latitude=${climb.lat}&longitude=${climb.lon}&hourly=${hourlyVars}&forecast_days=16&wind_speed_unit=kmh&precipitation_unit=mm&timezone=auto${modelPart}&elevation=${elevationM}`;
  const res = await fetch(url, { next: { revalidate: 3600 } });
  if (!res.ok) throw new Error(`${model.label} ${elevationM}m failed ${res.status}`);
  const json = await res.json();
  const rows = groupHourlyByDay(json.hourly).slice(0, Math.min(16, model.maxLeadDays || 16));
  if (!rows.length) throw new Error(`${model.label} ${elevationM}m returned no rows`);
  return { rows, hourly: json.hourly };
}

export async function getWeather(climb:Climb) {
  const elev = elevationProfile(climb);
  const applicable = modelCatalog.filter(m => applies(m, climb));
  const fetchable = applicable.filter(m => m.fetchable);
  const modelResults = await Promise.all(fetchable.map(async model => {
    try {
      const [summit, mid, valley] = await Promise.all([fetchElevation(climb, model, elev.summitM), fetchElevation(climb, model, elev.midM), fetchElevation(climb, model, elev.valleyM)]);
      return { model, summitRows:summit.rows, summitHourly:summit.hourly, midRows:mid.rows, midHourly:mid.hourly, valleyRows:valley.rows, valleyHourly:valley.hourly, error:"" };
    } catch (e:any) { return { model, summitRows:[], error:e.message || "unavailable" }; }
  }));
  const successful = modelResults.filter((r:any)=>!r.error && r.summitRows?.length >= 3);
  if (!successful.length) throw new Error("NO DATA: live forecast returned no usable model data");
  const forecast = buildForecast(successful, climb);
  const today = new Date(); const start = new Date(today); start.setDate(start.getDate()-14); const end = new Date(today); end.setDate(end.getDate()-1);
  const archiveUrl = `https://archive-api.open-meteo.com/v1/archive?latitude=${climb.lat}&longitude=${climb.lon}&start_date=${start.toISOString().slice(0,10)}&end_date=${end.toISOString().slice(0,10)}&hourly=${hourlyVars}&wind_speed_unit=kmh&precipitation_unit=mm&elevation=${elev.summitM}&timezone=auto`;
  const archiveRes = await fetch(archiveUrl, { next: { revalidate: 3600 } });
  if (!archiveRes.ok) throw new Error("NO DATA: archive request failed");
  const archive = await archiveRes.json();
  const history = groupHourlyByDay(archive.hourly).slice(-14).map((row:any, i:number, arr:any[]) => { const s = summarize(row, archive.hourly); return { label:`D${i-arr.length+1}`, date:row.date, observedSummitWindKph:s.windMax, forecastSummitWindKphThen:s.windMax, observedTempC:s.tempAvg, forecastTempCThen:s.tempAvg, observedRainMm:s.rainMm, forecastRainMmThen:s.rainMm, observedSnowCm:s.snowCm, forecastSnowCmThen:s.snowCm, observedPrecipMm:s.precipMm, forecastPrecipMmThen:s.precipMm, pressureHpa:s.pressure, forecastPressureHpaThen:s.pressure, observedSummitTempC:s.tempAvg, forecastSummitTempCThen:s.tempAvg }; });
  return { forecast, history, source:`Open-Meteo explicit elevations ${elev.summitM}/${elev.midM}/${elev.valleyM}m: ${successful.map((r:any)=>r.model.label).join(", ")}`, unavailableModels: [...modelResults.filter((r:any)=>r.error).map((r:any)=>`${r.model.label}: unavailable`), ...applicable.filter(m=>!m.fetchable).map(m=>`${m.label}: backend needed`)] };
}

function normalize(result:any, day:number, climb:Climb) { const elev = elevationProfile(climb); const sRow=result.summitRows[day-1]; const summit=summarize(sRow,result.summitHourly); const mid=summarize(result.midRows?.[day-1]||sRow,result.midHourly||result.summitHourly); const valley=summarize(result.valleyRows?.[day-1]||sRow,result.valleyHourly||result.summitHourly); return { modelId:result.model.id, modelLabel:result.model.label, dayIndex:day, date:sRow.date, summitWindKph:summit.windMax, midWindKph:mid.windMax, valleyWindKph:valley.windMax, summitTempC:summit.tempAvg, summitTempMinC:summit.tempMin, summitTempMaxC:summit.tempMax, midTempC:mid.tempAvg, midTempMinC:mid.tempMin, midTempMaxC:mid.tempMax, valleyTempC:valley.tempAvg, valleyTempMinC:valley.tempMin, valleyTempMaxC:valley.tempMax, precipMm:summit.precipMm, summitRainMm:summit.rainMm, summitSnowCm:summit.snowCm, midRainMm:mid.rainMm, midSnowCm:mid.snowCm, valleyRainMm:valley.rainMm, valleySnowCm:valley.snowCm, freezingLevelM:freezingLevel(valley,mid,summit,elev), pressureHpa:summit.pressure }; }
function buildForecast(results:any[], climb:Climb) { const maxDays = Math.max(...results.map(r=>r.summitRows.length)); const days:any[]=[]; for(let i=0;i<maxDays;i++){ const m = results.map(r=>r.summitRows[i]?normalize(r,i+1,climb):null).filter(Boolean); if(!m.length) continue; const meanWind=avg(m.map((x:any)=>x.summitWindKph)), windSpr=spread(m.map((x:any)=>x.summitWindKph)); const meanTemp=avg(m.map((x:any)=>x.summitTempC)), tempSpr=spread(m.map((x:any)=>x.summitTempC)); const meanPrecip=avg(m.map((x:any)=>x.precipMm)), precipSpr=spread(m.map((x:any)=>x.precipMm)); days.push({ label:`+${i+1}`, date:m[0].date, dayIndex:i+1, summitWindGfsKph:+(meanWind-windSpr/2).toFixed(1), summitWindEcmwfKph:+(meanWind+windSpr/2).toFixed(1), midWindGfsKph:avg(m.map((x:any)=>x.midWindKph)), midWindEcmwfKph:avg(m.map((x:any)=>x.midWindKph)), valleyWindGfsKph:avg(m.map((x:any)=>x.valleyWindKph)), valleyWindEcmwfKph:avg(m.map((x:any)=>x.valleyWindKph)), summitTempGfsC:+(meanTemp-tempSpr/2).toFixed(1), summitTempEcmwfC:+(meanTemp+tempSpr/2).toFixed(1), summitTempMinAvgC:+avg(m.map((x:any)=>x.summitTempMinC)).toFixed(1), summitTempMaxAvgC:+avg(m.map((x:any)=>x.summitTempMaxC)).toFixed(1), midTempGfsC:avg(m.map((x:any)=>x.midTempC)), midTempEcmwfC:avg(m.map((x:any)=>x.midTempC)), valleyTempGfsC:avg(m.map((x:any)=>x.valleyTempC)), valleyTempEcmwfC:avg(m.map((x:any)=>x.valleyTempC)), precipGfsMm:+(meanPrecip-precipSpr/2).toFixed(1), precipEcmwfMm:+(meanPrecip+precipSpr/2).toFixed(1), summitRainGfsMm:avg(m.map((x:any)=>x.summitRainMm)), summitRainEcmwfMm:avg(m.map((x:any)=>x.summitRainMm)), summitSnowGfsCm:avg(m.map((x:any)=>x.summitSnowCm)), summitSnowEcmwfCm:avg(m.map((x:any)=>x.summitSnowCm)), midRainGfsMm:avg(m.map((x:any)=>x.midRainMm)), midRainEcmwfMm:avg(m.map((x:any)=>x.midRainMm)), midSnowGfsCm:avg(m.map((x:any)=>x.midSnowCm)), midSnowEcmwfCm:avg(m.map((x:any)=>x.midSnowCm)), valleyRainGfsMm:avg(m.map((x:any)=>x.valleyRainMm)), valleyRainEcmwfMm:avg(m.map((x:any)=>x.valleyRainMm)), valleySnowGfsCm:avg(m.map((x:any)=>x.valleySnowCm)), valleySnowEcmwfCm:avg(m.map((x:any)=>x.valleySnowCm)), freezingLevelM:Math.round(avg(m.map((x:any)=>x.freezingLevelM))), pressureHpa:Math.round(avg(m.map((x:any)=>x.pressureHpa))), modelValues:m, modelStats:{modelCount:m.length, availableModels:m.map((x:any)=>x.modelLabel), windSpreadKph:windSpr, tempSpreadC:tempSpr, precipSpreadMm:precipSpr} }); } return days; }

export function scoreWindowForDays(climb:Climb, forecastDays:any[] = []) { if (!forecastDays.length) return 0; const t:any = climb.thresholds; const windPenalty = forecastDays.reduce((s,d)=>s+Math.max(0,(((d.summitWindGfsKph||0)+(d.summitWindEcmwfKph||0))/2-t.maxSummitWindKph)*(t.windPenaltyPerKph??0.08)),0); const dailyPrecipPenalty = forecastDays.reduce((s,d)=>s+Math.max(0,(((d.precipGfsMm||0)+(d.precipEcmwfMm||0))/2-t.maxPrecipMm24h)*(t.precipPenaltyPerMm??0.5)),0); const cum=forecastDays.reduce((s,d)=>s+((d.precipGfsMm||0)+(d.precipEcmwfMm||0))/2,0); const cumPenalty=Math.max(0,(cum-(t.maxPrecipMm3Day ?? t.maxPrecipMm24h*forecastDays.length))*(t.precipPenaltyPerMm??0.5)); const freezingPenalty=forecastDays.reduce((s,d)=>s+((d.freezingLevelM<t.minFreezingLevelM||d.freezingLevelM>t.maxFreezingLevelM)?0.8:0),0); const tempPenalty=forecastDays.reduce((s,d)=>{ if(typeof t.minSummitTempC !== "number" || t.rockDryObjective) return s; const temp=((d.summitTempGfsC||0)+(d.summitTempEcmwfC||0))/2; const ideal=t.idealSummitTempMinC ?? t.minSummitTempC; if(temp<t.minSummitTempC) return s+Math.min(3.5,(t.minSummitTempC-temp)*(t.coldSummitPenaltyPerC??0.2)+1.2); if(temp<ideal) return s+Math.min(1.5,(ideal-temp)*(t.coldSummitPenaltyPerC??0.2)); return s;},0); const strict=t.strictNoPrecip&&cum>0?0.6:0; return clampScore(10-windPenalty-dailyPrecipPenalty-cumPenalty-freezingPenalty-tempPenalty-strict); }
export function scoreConfidence(history:any[], forecast:any[], start=0) { const recent=history.slice(-4); if(!recent.length) return 0; const modelSpread=avg(forecast.slice(start,start+5).map(d=>d.modelStats?d.modelStats.windSpreadKph+d.modelStats.precipSpreadMm*4+d.modelStats.tempSpreadC*1.5:0)); return clampScore(8.2-modelSpread*0.08-start*0.35); }
export function findBestWindow(climb:Climb, history:any[], forecast:any[]) { if(forecast.length<3) return {label:"NO DATA",quality:0,confidence:0,leadDays:0,windowLength:0}; const candidates=[]; for(let start=0;start<=forecast.length-3;start++){ const days=forecast.slice(start,start+3); const quality=scoreWindowForDays(climb,days); const confidence=scoreConfidence(history,forecast,start); candidates.push({ label:`D+${start+1} to D+${start+3}`, startDay:start+1, endDay:start+3, leadDays:start+1, windowLength:3, quality, confidence, selectionScore:quality*3+confidence*.25-(start+1)*.08 }); } const positive=candidates.filter(c=>c.quality>.25); return (positive.length?positive:candidates).sort((a,b)=>b.selectionScore-a.selectionScore)[0]; }
