import { NextResponse } from "next/server";
export const dynamic = "force-dynamic";
const MODEL_CATALOG = [
  { id:"gfs",label:"GFS",provider:"NOAA via Open-Meteo GFS API",regions:["global"],maxLeadDays:16,endpoint:"https://api.open-meteo.com/v1/gfs",models:"gfs_seamless",weight:.85 },
  { id:"gfs_hrrr",label:"HRRR",provider:"NOAA HRRR via Open-Meteo GFS API",regions:["usa"],maxLeadDays:2,endpoint:"https://api.open-meteo.com/v1/gfs",models:"hrrr",weight:1.25 },
  { id:"nam_conus",label:"NAM",provider:"NOAA GRIB/NOMADS connector required",regions:["usa"],maxLeadDays:4,endpoint:null,note:"NAM is explicit NO DATA in this build; requires GRIB/NOMADS parser or third-party API.",weight:1.05 },
  { id:"noaa_rap",label:"RAP",provider:"NOAA GRIB/NOMADS connector required",regions:["usa"],maxLeadDays:1,endpoint:null,note:"RAP is explicit NO DATA in this build; requires GRIB/NOMADS parser or third-party API.",weight:1.1 },
  { id:"gem_global",label:"GEM Global / GDPS",provider:"ECCC via Open-Meteo GEM API",regions:["global"],maxLeadDays:10,endpoint:"https://api.open-meteo.com/v1/gem",models:"gem_global",weight:.9 },
  { id:"gem_regional",label:"GEM Regional / RDPS",provider:"ECCC via Open-Meteo GEM API",regions:["canada"],maxLeadDays:3.5,endpoint:"https://api.open-meteo.com/v1/gem",models:"gem_regional",weight:1.15 },
  { id:"gem_hrdps_continental",label:"HRDPS Continental",provider:"ECCC via Open-Meteo GEM API",regions:["canada"],maxLeadDays:2,endpoint:"https://api.open-meteo.com/v1/gem",models:"gem_hrdps_continental",weight:1.25 },
  { id:"ecmwf_ifs025",label:"ECMWF IFS",provider:"ECMWF via Open-Meteo ECMWF API",regions:["global"],maxLeadDays:15,endpoint:"https://api.open-meteo.com/v1/ecmwf",models:"ifs025",weight:1.05 },
  { id:"ecmwf_aifs025",label:"ECMWF AIFS",provider:"ECMWF via Open-Meteo ECMWF API",regions:["global"],maxLeadDays:15,endpoint:"https://api.open-meteo.com/v1/ecmwf",models:"aifs025",weight:.95 },
];
const HOURLY="temperature_2m,wind_speed_10m,wind_gusts_10m,precipitation,rain,snowfall,pressure_msl,freezing_level_height";
const ARCHIVE_HOURLY="temperature_2m,precipitation,rain,snowfall,pressure_msl,wind_speed_10m";
const isNum=(v:any)=>typeof v==="number"&&Number.isFinite(v); const clean=(a:any[])=>a.filter(isNum);
const avg=(a:any[])=>{const c=clean(a);return c.length?c.reduce((s,v)=>s+v,0)/c.length:null};
const sum=(a:any[])=>clean(a).reduce((s,v)=>s+v,0); const max=(a:any[])=>{const c=clean(a);return c.length?Math.max(...c):null}; const min=(a:any[])=>{const c=clean(a);return c.length?Math.min(...c):null}; const spread=(a:any[])=>{const c=clean(a);return c.length>1?Math.max(...c)-Math.min(...c):0};
const weightedAvg=(items:any[])=>{const v=items.filter(i=>isNum(i.value)&&isNum(i.weight)&&i.weight>0); const t=v.reduce((s,i)=>s+i.weight,0); return t?v.reduce((s,i)=>s+i.value*i.weight,0)/t:null};
function applies(m:any,region:string){return m.regions.includes("global")||m.regions.includes(region)}
function dateStr(d:Date){return d.toISOString().slice(0,10)} function dayKey(t:string){return String(t).slice(0,10)}
async function delay(ms:number){return new Promise(r=>setTimeout(r,ms))}
async function fetchJson(url:string, attempts=3){let last=""; for(let i=0;i<attempts;i++){const r=await fetch(url,{headers:{"User-Agent":"mountain-window-app/2.0"},cache:"no-store"}); const txt=await r.text(); let j:any={}; try{j=JSON.parse(txt)}catch{j={raw:txt}}; if(r.ok)return j; last=j.reason||j.error||`${r.status} ${r.statusText}: ${txt.slice(0,160)}`; if(r.status===429||/concurrent|rate|too many/i.test(last)){await delay(800*(i+1)); continue} break} throw new Error(last||"request failed")}
function urlFor(m:any,lat:number,lon:number,summitM:number){ if(!m.endpoint)return null; const u=new URL(m.endpoint); u.searchParams.set("latitude",String(lat)); u.searchParams.set("longitude",String(lon)); u.searchParams.set("hourly",HOURLY); u.searchParams.set("wind_speed_unit","kmh"); u.searchParams.set("precipitation_unit","mm"); u.searchParams.set("timezone","auto"); u.searchParams.set("forecast_days",String(Math.min(16,Math.ceil(m.maxLeadDays)))); u.searchParams.set("elevation",String(Math.round(summitM))); if(m.models)u.searchParams.set("models",m.models); return u.toString() }
function summarize(m:any,date:string,idx:number[],h:any){ const pick=(k:string)=>idx.map(i=>h[k]?.[i]).filter(isNum); const temps=pick("temperature_2m"), wind=pick("wind_speed_10m"), gust=pick("wind_gusts_10m"), prec=pick("precipitation"), rain=pick("rain"), snow=pick("snowfall"), pressure=pick("pressure_msl"), freeze=pick("freezing_level_height"); const w=max(gust)??max(wind); const t=avg(temps); if(!isNum(t)&&!isNum(w)&&prec.length===0)return null; return {modelId:m.id,modelLabel:m.label,provider:m.provider,weight:m.weight,dayIndex:null,date,summitWindKph:w,midWindKph:isNum(w)?w*.75:null,valleyWindKph:isNum(w)?w*.45:null,summitTempC:t,summitTempMinC:min(temps),summitTempMaxC:max(temps),midTempC:isNum(t)?t+5:null,valleyTempC:isNum(t)?t+10:null,precipMm:sum(prec),summitRainMm:sum(rain),summitSnowCm:sum(snow),midRainMm:sum(rain),midSnowCm:sum(snow),valleyRainMm:sum(rain),valleySnowCm:sum(snow),pressureHpa:avg(pressure),freezingLevelM:avg(freeze)} }
async function fetchModel(m:any,lat:number,lon:number,summitM:number){ if(!m.endpoint)throw new Error(m.note||"connector not implemented"); const j=await fetchJson(urlFor(m,lat,lon,summitM)!); if(!j.hourly||!Array.isArray(j.hourly.time))throw new Error(j.reason||j.error||"No hourly data returned"); const by=new Map<string,number[]>(); j.hourly.time.forEach((t:string,i:number)=>{const k=dayKey(t); if(!by.has(k))by.set(k,[]); by.get(k)!.push(i)}); const daily=[...by.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([d,idx],i)=>{const x:any=summarize(m,d,idx,j.hourly); if(x)x.dayIndex=i+1; return x}).filter(Boolean).filter((d:any)=>d.dayIndex<=Math.ceil(m.maxLeadDays)); if(!daily.length)throw new Error("No usable daily rows after grouping"); return {model:m,daily} }
function aggregate(results:any[]){ const maxDays=Math.max(...results.map(r=>r.daily.length)); const days:any[]=[]; for(let i=0;i<maxDays;i++){const vals=results.map(r=>{const d=r.daily[i]; if(!d||d.dayIndex>Math.ceil(r.model.maxLeadDays))return null; return d}).filter(Boolean); if(!vals.length)continue; const w=(k:string)=>weightedAvg(vals.map((m:any)=>({value:m[k],weight:m.weight||1})))??0; const a=(k:string)=>avg(vals.map((m:any)=>m[k]))??0; const sw=w("summitWindKph"), mt=w("summitTempC"), precip=w("precipMm"), ws=spread(vals.map((m:any)=>m.summitWindKph)), ts=spread(vals.map((m:any)=>m.summitTempC)), ps=spread(vals.map((m:any)=>m.precipMm)); days.push({label:`+${i+1}`,dayIndex:i+1,date:vals[0].date,summitWindGfsKph:+(sw-ws/2).toFixed(1),summitWindEcmwfKph:+(sw+ws/2).toFixed(1),midWindGfsKph:+(w("midWindKph")-spread(vals.map((m:any)=>m.midWindKph))/2).toFixed(1),midWindEcmwfKph:+(w("midWindKph")+spread(vals.map((m:any)=>m.midWindKph))/2).toFixed(1),valleyWindGfsKph:+(w("valleyWindKph")-spread(vals.map((m:any)=>m.valleyWindKph))/2).toFixed(1),valleyWindEcmwfKph:+(w("valleyWindKph")+spread(vals.map((m:any)=>m.valleyWindKph))/2).toFixed(1),summitTempGfsC:+(mt-ts/2).toFixed(1),summitTempEcmwfC:+(mt+ts/2).toFixed(1),summitTempMinAvgC:+(a("summitTempMinC")||mt).toFixed(1),summitTempMaxAvgC:+(a("summitTempMaxC")||mt).toFixed(1),midTempGfsC:+(w("midTempC")-spread(vals.map((m:any)=>m.midTempC))/2).toFixed(1),midTempEcmwfC:+(w("midTempC")+spread(vals.map((m:any)=>m.midTempC))/2).toFixed(1),valleyTempGfsC:+(w("valleyTempC")-spread(vals.map((m:any)=>m.valleyTempC))/2).toFixed(1),valleyTempEcmwfC:+(w("valleyTempC")+spread(vals.map((m:any)=>m.valleyTempC))/2).toFixed(1),precipGfsMm:+(precip-ps/2).toFixed(1),precipEcmwfMm:+(precip+ps/2).toFixed(1),summitRainGfsMm:+w("summitRainMm").toFixed(1),summitRainEcmwfMm:+w("summitRainMm").toFixed(1),summitSnowGfsCm:+w("summitSnowCm").toFixed(1),summitSnowEcmwfCm:+w("summitSnowCm").toFixed(1),freezingLevelM:Math.round(w("freezingLevelM")),pressureHpa:Math.round(w("pressureHpa")),modelStats:{modelCount:vals.length,availableModels:vals.map((m:any)=>m.modelLabel),weightedModels:vals.map((m:any)=>`${m.modelLabel} (${m.weight})`),windSpreadKph:+ws.toFixed(1),tempSpreadC:+ts.toFixed(1),precipSpreadMm:+ps.toFixed(1)},modelValues:vals.map((m:any)=>({modelId:m.modelId,modelLabel:m.modelLabel,provider:m.provider,weight:m.weight,dayIndex:m.dayIndex,date:m.date,summitWindKph:m.summitWindKph,midWindKph:m.midWindKph,valleyWindKph:m.valleyWindKph,summitTempC:m.summitTempC,summitTempMinC:m.summitTempMinC,summitTempMaxC:m.summitTempMaxC,midTempC:m.midTempC,valleyTempC:m.valleyTempC,precipMm:m.precipMm,summitRainMm:m.summitRainMm,summitSnowCm:m.summitSnowCm,freezingLevelM:m.freezingLevelM,pressureHpa:m.pressureHpa}))}) } return days }
async function history(lat:number,lon:number,summitM:number){const end=new Date(); end.setDate(end.getDate()-1); const start=new Date(end); start.setDate(start.getDate()-13); const u=new URL("https://archive-api.open-meteo.com/v1/archive"); u.searchParams.set("latitude",String(lat)); u.searchParams.set("longitude",String(lon)); u.searchParams.set("start_date",dateStr(start)); u.searchParams.set("end_date",dateStr(end)); u.searchParams.set("hourly",ARCHIVE_HOURLY); u.searchParams.set("wind_speed_unit","kmh"); u.searchParams.set("precipitation_unit","mm"); u.searchParams.set("timezone","auto"); u.searchParams.set("elevation",String(Math.round(summitM))); try{const j=await fetchJson(u.toString(),2); if(!j.hourly?.time)return []; const by=new Map<string,number[]>(); j.hourly.time.forEach((t:string,i:number)=>{const k=dayKey(t); if(!by.has(k))by.set(k,[]); by.get(k)!.push(i)}); return [...by.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,idx])=>({label:date,date,observedPrecipMm:sum(idx.map(i=>j.hourly.precipitation?.[i])),observedWindKph:max(idx.map(i=>j.hourly.wind_speed_10m?.[i])),pressureHpa:avg(idx.map(i=>j.hourly.pressure_msl?.[i])),observedTempAvgC:avg(idx.map(i=>j.hourly.temperature_2m?.[i])),observedTempMinC:min(idx.map(i=>j.hourly.temperature_2m?.[i])),observedTempMaxC:max(idx.map(i=>j.hourly.temperature_2m?.[i]))}))}catch{return []}}
export async function GET(req:Request){const u=new URL(req.url); const lat=Number(u.searchParams.get("lat")), lon=Number(u.searchParams.get("lon")), summitM=Number(u.searchParams.get("summitM")); const region=u.searchParams.get("region")||"global"; if(!Number.isFinite(lat)||!Number.isFinite(lon)||!Number.isFinite(summitM))return NextResponse.json({error:"Missing or invalid lat/lon/summitM query parameters"},{status:400}); const models=MODEL_CATALOG.filter(m=>applies(m,region)); const successful:any[]=[]; const unavailableModels:string[]=[]; for(const m of models){try{successful.push(await fetchModel(m,lat,lon,summitM)); await delay(175)}catch(e:any){unavailableModels.push(`${m.label}: ${e?.message||"unavailable"}`)}} if(!successful.length)return NextResponse.json({error:"No direct model feeds returned usable data",unavailableModels},{status:502}); return NextResponse.json({source:"Direct Open-Meteo national-model feeds. Elevation parameter is set to objective summit where supported. NAM/RAP are explicit NO DATA until a NOAA GRIB parser or alternate API is added.",unavailableModels,history:await history(lat,lon,summitM),forecast:aggregate(successful)})}
