import { NextResponse } from "next/server";
export const dynamic = "force-dynamic";
const AVCAN_BASE="https://avcan-services-api.prod.avalanche.ca";
const ratingMap:Record<string,number>={norating:0,noRating:0,low:1,moderate:2,considerable:3,high:4,extreme:5};
function stripHtml(html?:string|null){return (html||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();}
function normalizeRating(value:any){ if(!value) return 0; if(typeof value==="string") return ratingMap[value]??ratingMap[value.toLowerCase()]??0; if(typeof value?.value==="string") return ratingMap[value.value]??ratingMap[value.value.toLowerCase()]??0; return 0; }
function buildSummary(history:any[], headline:string){ const last=history[history.length-1]||{alpine:0,problems:[]}; const persistentDays=history.filter(d=>(d.problems||[]).some((p:string)=>/persistent/i.test(p))).length; const windSlabDays=history.filter(d=>(d.problems||[]).some((p:string)=>/wind slab/i.test(p))).length; return {last,persistentDays,windSlabDays,headline:headline||"Live avalanche bulletin loaded.",riskScore:Math.max(0,Math.min(10,(last.alpine||0)*2.2+persistentDays*0.25))}; }
async function fetchAvCan(lat:string,lon:string){ const res=await fetch(`${AVCAN_BASE}/forecasts/en/products/point?lat=${encodeURIComponent(lat)}&long=${encodeURIComponent(lon)}`,{next:{revalidate:1800}}); if(!res.ok) throw new Error(`Avalanche Canada point forecast failed: ${res.status}`); const product=await res.json(); const p=Array.isArray(product)?product[0]:product; const report=p?.report; if(!report) throw new Error("Avalanche Canada returned no forecast report for this point"); const headline=stripHtml(report.highlights)||stripHtml(report.message)||stripHtml(report.summaries?.[0]?.content)||"Avalanche Canada bulletin loaded."; const problems=Array.isArray(report.problems)?report.problems.map((x:any)=>x?.type?.display||x?.type?.value||x?.display||x?.value||x?.name).filter(Boolean):[]; const ratings=Array.isArray(report.dangerRatings)?report.dangerRatings:[]; const avalancheHistory=ratings.map((d:any,i:number)=>({label:d?.date?.display||d?.date?.value?.slice(0,10)||`Day ${i+1}`,date:d?.date?.value||"",alpine:normalizeRating(d?.ratings?.alp?.rating),treeline:normalizeRating(d?.ratings?.tln?.rating),belowTreeline:normalizeRating(d?.ratings?.btl?.rating),problems,note:headline})); const noRating=/not issued|spring conditions|no rating|summer/i.test(headline)||avalancheHistory.every((d:any)=>d.alpine===0&&d.treeline===0); const statusHeadline=noRating?`Avalanche Canada: ${headline||"No rated avalanche forecast is currently issued for this point."}`:headline; return {status:noRating?"seasonal-or-no-rating":"live",source:`Avalanche Canada${p?.url?` · ${p.url}`:""}`,avalancheHistory,summary:buildSummary(avalancheHistory,statusHeadline),raw:{url:p?.url,reportTitle:report.title,dateIssued:report.dateIssued,validUntil:report.validUntil}}; }
function nwacSeasonal(){ return {status:"seasonal-or-unavailable",source:"NWAC",avalancheHistory:[],summary:{headline:"NWAC live avalanche bulletin integration is not enabled in this build, or forecasts may be out of season. Review NWAC directly for current spring statements.",riskScore:0,last:{alpine:0,problems:[]},persistentDays:0,windSlabDays:0}}; }
export async function GET(req:Request){ const sp=new URL(req.url).searchParams; const lat=sp.get("lat"); const lon=sp.get("lon"); const region=sp.get("region"); if(!lat||!lon) return NextResponse.json({error:"Missing lat/lon"},{status:400}); if(region==="canada"||region==="global"){ try{return NextResponse.json(await fetchAvCan(lat,lon));}catch(e:any){ return NextResponse.json({status:"unavailable",source:"Avalanche Canada",avalancheHistory:[],summary:{headline:e?.message||"Live Avalanche Canada data unavailable.",riskScore:0,last:{alpine:0,problems:[]},persistentDays:0,windSlabDays:0}});} } return NextResponse.json(nwacSeasonal()); }
